version: '3.8'
services:

  postgres:
    build:
      context: ${PWD}/docker/postgres
    env_file: ${PWD}/docker/postgres/.env
    container_name: postgres

  astromodel:
    build:
      context: ${PWD}/docker/astromodel
    container_name: astromodel

  wsserver:
    build:
      context: ${PWD}/docker/wsserver
    container_name: wsserver

  wsclient:
    build:
      context: ${PWD}

  nginx:
    image: nginx
    ports:
      - 8888:8888
    depends_on:
      - wsserver
    volumes:
      - ${PWD}/astromodel.conf:/etc/nginx/conf.d/default.conf
      - /var/astromodel/data:/data
      - ${PWD}/configurator:/configurator
      - ${PWD}/server/www:/www
    container_name: nginx