# This is main problem configuration file. It has special
# name 'config.yml' and you SHOULDN'T RENAME it. The file
# contains all information about variables, which will be
# used in current problem. To generate web from of this
# problem you must to have this file in problem folder.
# In this web form user can put his paremeters and run
# solver of current problem. This file also is necessary
# to parse incomming parameters from web form. You can
# specify any web field to make parameters more flexable.
#
# This file has special structure. There are four special
# keywords: ('UNITS', 'CASES', 'GENERAL', 'OBJECTS').
# You must write it only in this order.
#
# keyword 'UNITS':
#  Description:
#      This group contains all types of units you need. If
#      you don't need any units, just skip this keyword.
#
#      Name {unit} uses to 'CASES.{name}.units: {unit}' value
#      (check 'CASES' keyword example). Names of units must
#      consist of lowercase latin letters ONLY.
#
#      Names {unit} and {subunit} can consist of ANY characters
#      like russian, spaces, slashes, dashes and other...
#      This names will be displayed in web form as name of
#      unit and it's derivatives.
#
#      Value {number} must be in special numeric sturcure
#      like '(m)e±(n)', where 'm' and 'n' are mantissa
#      and exponent respectively ('m' and 'n' belongs 'Z')
#      Base is always 10, because structure of '(m)e±(n)'
#      means m * 10^n.
#
#      Often subunit {number} is 3*k more/less than
#      base unit exponent as derived unit, like kilo-, mega-,
#      milli- and other... ('k' belongs 'Z').
#
#      BUT subunit value can be ANY number with '(m)e±(n)'
#      structure (ex. 'time' unit can't have megaseconds,
#      use days or hours, or other non-SI units).
#
#      OR you can write a number {number} WITHOUT '(m)e±(n)'
#      structure. If you need this, add double quotes like "3.14159".
#  Example:
#
# UNITS:
#   {name}:
#     {unit}: {number}
#     {subunit}: {number}
#     {subunit}: {number}
#     ...
#   ...
#
# keyword 'CASES':
#  Description:
#      This group contains all variables (cases) you need to
#      solve problem. This cases never appears by themselves,
#      because they are the parts of 'GENERAL' and 'OBJECTS'
#      keyword structures.
#
#      Name of cases must consist of owercase latin letters ONLY.
#      Name of cases uses for 'GENERAL' and 'OBJECTS' keywords
#      (check 'GENERAL' and 'OBJECTS' description below).
#
#      Single case MUST contains this keys:
#      ('title', 'default', 'type', 'class', 'dementional').
#      Cases can also have optional keys:
#      ('units', 'minimum', 'maximum', 'cases').
#
#      Key 'title' is a string and can
#      consist of ANY characters like russian, spaces, slashes,
#      dashes and other... This key will be displayed in web
#      form as name of current case.
#
#      Key 'default' is a string with default value, which is
#      necessary if something goes wrong while parsing. If
#      'default' value is numeric, you MUST add double
#      quotes like "2.71828".
#
#      Key 'type' must be one of next values: ('str', 'bool',
#      'float', 'int', 'expr'). Parser gets this value to define
#      python type of current variable.
#
#      Key 'class' must be one of next
#      values: ('dropdown', 'checkbox', 'number', 'text'). This
#      key is necessary to generate web form automaticly. This
#      key defines the way, how currnet parameter will be
#      entered by user.
#
#      Key 'dementional' is a boolean value
#      which shows is this a vector or scalar variable
#      ('true' or 'false' respectively).
#
#      Optional keys 'minimum' and 'maximum' are used only if
#      'class: number'. Key 'minimum' is the lowerbound and
#      key 'maximum' is the upperbound.
#
#      Optional key 'units' is used only if 'class: number'. This
#      key must be one of the 'UNITS' varuables. If you use some
#      unit system, you need to define this units in 'UNITS' group
#      (check 'UNITS' description above).
#
#      Optional key 'cases' is used only if 'class: dropdown'. This
#      key is necessary to create all possible options, which current
#      variable can take.
#      The {title} parameter inside of 'cases' key is the name,
#      which will be displayed in web form as name of the current
#      option.
#      Parameter {value} is the option (state), which current
#      case can take.
#  Example:
#
# CASES:
#   {name}:
#     title: {title}
#     default: {default}
#     type: {str / bool / float / int / expr}
#     class: {dropdown / checkbox / number / text}
#     dementional: {true / false}
#     [units]: {units}
#     [minimum]: {number}
#     [maximum]: {number}
#     [cases]:
#       {title}: {value}
#       {title}: {value}
#       ...
#   ...
#
# keyword 'GENERAL':
#  Description:
#      This group contains some of the cases, which was written
#      for general parameters (like time step or size of
#      calculating area).
#
#      Every {case} parameter is the one of 'CASES' group names.
#      In code you can get parsed case value by calling it's name
#      (ex. 'variable = config.{name}').
#  Example:
#
# GENERAL:
#  - {case}
#  - {case}
#  - {case}
# ...
#
# keyword 'OBJECTS':
#  Description:
#      This group contains object types, which you will use to
#      solve your problem. Every object must have 'title' key and
#      'cases' key.
#
#      Key 'title' will be displayed in web form as
#      name of current object.
#
#      Key 'cases' contains names of 'CASES' exactly as in
#      'GENERAL' group. In code you can call any of this cases
#      (ex. 'array = [obj.{case} for obj in config.{name}]')
#  Example:
#
# OBJECTS:
#   {name}:
#     title: {title}
#     cases:
#       - {case}
#       - {case}
#       - {case}
#      ...
#   ...

UNITS:
    units_one:
        hint: Еденицы измерения 1
        default: метры
        values:
            микрометры: 1e-6
            милиметры: 1e-3
            метры: 1e+0
            километры: 1e+3
            aстрономические единицы: 1495978707e+2
            световые года: 94607304725808e+2
            парсеки: 30856776e+9
            мегапарсеки: 30856776e+15

CASES:
    number_of_cells:
        title: Количество клеток
        default: "10"
        type: int
        class: number
        minimum: "0"
        dementional: false
        hint: Количество клеток вдоль одной оси. Вся область будет иметь N^2 клеток

    number_of_frames:
        title: Количество шагов моделирования
        default: "100"
        type: int
        class: number
        dementional: false
        hint: Время моделирования эволюции клеточных автоматов

    frames_interval:
        title: Интервал между кадрами (в мс)
        default: "300"
        type: int
        class: number
        dementional: false
        hint: Аналогично FPS. В случае когда FPS 25 кадров в секунду, интервал = 1 / 25 = 0.04 = 40 мс

    
    model:
        title: Модель клеточного автомата
        default: "0"
        type: int
        class: dropdown
        cases:
            Игра жизнь: "0"
            Лесной пожар: "1"
        dementional: false
        hint: По умолчанию установлена "Игра Жизнь"
    
    output_flag:
        title: Вывод результата
        default: "0"
        type: int
        class: dropdown
        cases:
            Анимация моедли: "0"
            Изображение начальной конфигурации: "1"
        dementional: false
        hint: По умолчанию установлена анимация модели

    ####################### point_objects #######################
    x_coord:
        title: Координата клетки по оси ОХ
        default: "0"
        type: int
        class: number
        dementional: false
        hint: Определите координату клетки по оси ОХ

    y_coord:
        title: Координата клетки по оси ОY
        default: "0"
        type: int
        class: number
        dementional: false
        hint: Определите координату клетки по оси ОY

    square_coord_x:
        title: Координата Х левого нижнего края квадрата
        default: "0"
        type: int
        class: number
        dementional: false
        hint: Определите координату Х левого нижнего края квадрата
    
    square_coord_y:
        title: Координата X левого нижнего края квадрата
        default: "0"
        type: int
        class: number
        dementional: false
        hint: Определите координату Y левого нижнего края квадрата

    line_coord_x:
        title: Координата X левого/нижнего края линии
        default: "0"
        type: int
        class: number
        dementional: false
        hint: Определите координату X левого/нижнего края линии

    line_coord_y:
        title: Координата Y левого/нижнего края линии
        default: "0"
        type: int
        class: number
        dementional: false
        hint: Определите координату Y левого/нижнего края квадрата

    line_orientation:
        title: Ориентация линии
        default: "0"
        type: int
        class: dropdown
        cases:
            Горизонтальное расположение: "0"
            Вертикальное расположение: "1"
        dementional: false
        hint: Выберите начальную ориентацию линии
    
    fire_coord_x:
        title: Координата X клетки пожара
        default: "0"
        type: int
        class: number
        dementional: false
        hint: Клекта с которой начинается пожар

    fire_coord_y:
        title: Координата Y клетки пожара
        default: "0"
        type: int
        class: number
        dementional: false
        hint: Клекта с которой начинается пожар
    

GENERAL:
    - number_of_cells
    - number_of_frames
    - frames_interval
    - model
    - output_flag


OBJECTS:
    single_cellulars:
        color: false
        title: Одиночная клетка
        cases:
            - x_coord
            - y_coord
    
    squares:
        color: false
        title: Квадрат (4 клекти)
        cases:
            - square_coord_x
            - square_coord_y
    
    lines:
        color: false
        title: Линия (3 клетки)
        cases:
            - line_coord_x
            - line_coord_y
            - line_orientation
    
    fires:
        color: false
        title: Пожар (только для модели "Лесной пожар")
        cases:
            - fire_coord_x
            - fire_coord_y