version: "3.8"

services:
    config:
        image: nginx
        environment:
            - PROBLEM=${PROBLEM}
        ports:
            - 8008:8008
        volumes:
            - ${PWD}/docker/boot/nginx.conf:/etc/nginx/templates/default.conf.template
            - ${PWD}/frontend:/etc/nginx/html/frontend
        container_name: config
