version: '3.8'

services:
  tester:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/Dockerfile
      target: tester
    container_name: tester
    volumes:
      - ${FOLDER}/:/usr/src/folder/
