version: "3.8"

services:
    tester:
        build:
            context: ${PWD}
            dockerfile: ${PWD}/docker/Dockerfile
            target: tester
        container_name: tester
        cap_add:
            - SYS_PTRACE
        volumes:
            - ${FOLDER}/:/usr/src/folder/
