
CASES:

  fenics:
    title: Включить библиотеку "fenics" в тестирование?
    default: 'False'
    type: bool
    class: checkbox
    dementional: false

  dolfin:
    title: Включить библиотеку "dolfin" в тестирование?
    default: 'False'
    type: bool
    class: checkbox
    dementional: false

  mshr:
    title: Включить библиотеку "mshr" в тестирование?
    default: 'False'
    type: bool
    class: checkbox
    dementional: false

  leopart:
    title: Включить библиотеку "leopart" в тестирование?
    default: 'False'
    type: bool
    class: checkbox
    dementional: false

GENERAL:

  - fenics
  - dolfin
  - mshr
  - leopart
