version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ${PWD}/docker/nginx/Dockerfile
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ${PWD}/server/www:/www
      - ${PWD}/server/configurator:/configurator
      - /var/astromodel/data:/data

networks:
  default:
    external:
      name: astro-net