
# This is main problem configuration file. It has special
# name 'config.yml' and you SHOULDN'T RENAME it. The file
# contains all information about variables, which will be
# used in current problem. To generate web from of this
# problem you must to have this file in problem folder.
# In this web form user can put his paremeters and run
# solver of current problem. This file also is necessary
# to parse incomming parameters from web form. You can
# specify any web field to make parameters more flexable.
#
# This file has special structure. There are four special
# keywords: ('UNITS', 'CASES', 'GENERAL', 'OBJECTS').
# You must write it only in this order.
#
# keyword 'UNITS':
#  Description:
#      This group contains all types of units you need. If
#      you don't need any units, just skip this keyword.
#
#      Name {unit} uses to 'CASES.{name}.units: {unit}' value
#      (check 'CASES' keyword example). Names of units must
#      consist of lowercase latin letters ONLY.
#
#      Names {unit} and {subunit} can consist of ANY characters
#      like russian, spaces, slashes, dashes and other...
#      This names will be displayed in web form as name of
#      unit and it's derivatives.
#
#      Value {number} must be in special numeric sturcure
#      like '(m)e±(n)', where 'm' and 'n' are mantissa
#      and exponent respectively ('m' and 'n' belongs 'Z')
#      Base is always 10, because structure of '(m)e±(n)'
#      means m * 10^n.
#
#      Often subunit {number} is 3*k more/less than
#      base unit exponent as derived unit, like kilo-, mega-,
#      milli- and other... ('k' belongs 'Z').
#
#      BUT subunit value can be ANY number with '(m)e±(n)'
#      structure (ex. 'time' unit can't have megaseconds,
#      use days or hours, or other non-SI units).
#
#      OR you can write a number {number} WITHOUT '(m)e±(n)'
#      structure. If you need this, add double quotes like "3.14159".
#  Example:
#
# UNITS:
#   {name}:
#     {unit}: {number}
#     {subunit}: {number}
#     {subunit}: {number}
#     ...
#   ...
#
# keyword 'CASES':
#  Description:
#      This group contains all variables (cases) you need to
#      solve problem. This cases never appears by themselves,
#      because they are the parts of 'GENERAL' and 'OBJECTS'
#      keyword structures.
#
#      Name of cases must consist of owercase latin letters ONLY.
#      Name of cases uses for 'GENERAL' and 'OBJECTS' keywords
#      (check 'GENERAL' and 'OBJECTS' description below).
#
#      Single case MUST contains this keys:
#      ('title', 'default', 'type', 'class', 'dementional').
#      Cases can also have optional keys:
#      ('units', 'minimum', 'maximum', 'cases').
#
#      Key 'title' is a string and can
#      consist of ANY characters like russian, spaces, slashes,
#      dashes and other... This key will be displayed in web
#      form as name of current case.
#
#      Key 'default' is a string with default value, which is
#      necessary if something goes wrong while parsing. If
#      'default' value is numeric, you MUST add double
#      quotes like "2.71828".
#
#      Key 'type' must be one of next values: ('str', 'bool',
#      'float', 'int', 'expr'). Parser gets this value to define
#      python type of current variable.
#
#      Key 'class' must be one of next
#      values: ('dropdown', 'checkbox', 'number', 'text'). This
#      key is necessary to generate web form automaticly. This
#      key defines the way, how currnet parameter will be
#      entered by user.
#
#      Key 'dementional' is a boolean value
#      which shows is this a vector or scalar variable
#      ('true' or 'false' respectively).
#
#      Optional keys 'minimum' and 'maximum' are used only if
#      'class: number'. Key 'minimum' is the lowerbound and
#      key 'maximum' is the upperbound.
#
#      Optional key 'units' is used only if 'class: number'. This
#      key must be one of the 'UNITS' varuables. If you use some
#      unit system, you need to define this units in 'UNITS' group
#      (check 'UNITS' description above).
#
#      Optional key 'cases' is used only if 'class: dropdown'. This
#      key is necessary to create all possible options, which current
#      variable can take.
#      The {title} parameter inside of 'cases' key is the name,
#      which will be displayed in web form as name of the current
#      option.
#      Parameter {value} is the option (state), which current
#      case can take.
#  Example:
#
# CASES:
#   {name}:
#     title: {title}
#     default: {default}
#     type: {str / bool / float / int / expr}
#     class: {dropdown / checkbox / number / text}
#     dementional: {true / false}
#     [units]: {units}
#     [minimum]: {number}
#     [maximum]: {number}
#     [cases]:
#       {title}: {value}
#       {title}: {value}
#       ...
#   ...
#
# keyword 'GENERAL':
#  Description:
#      This group contains some of the cases, which was written
#      for general parameters (like time step or size of
#      calculating area).
#
#      Every {case} parameter is the one of 'CASES' group names.
#      In code you can get parsed case value by calling it's name
#      (ex. 'variable = config.{name}').
#  Example:
#
# GENERAL:
#  - {case}
#  - {case}
#  - {case}
# ...
#
# keyword 'OBJECTS':
#  Description:
#      This group contains object types, which you will use to
#      solve your problem. Every object must have 'title' key and
#      'cases' key.
#
#      Key 'title' will be displayed in web form as
#      name of current object.
#
#      Key 'cases' contains names of 'CASES' exactly as in
#      'GENERAL' group. In code you can call any of this cases
#      (ex. 'array = [obj.{case} for obj in config.{name}]')
#  Example:
#
# OBJECTS:
#   {name}:
#     title: {title}
#     cases:
#       - {case}
#       - {case}
#       - {case}
#      ...
#   ...

UNITS:

  distance:
    микрометры: 1e-6
    милиметры: 1e-3
    метры: 1e+0
    километры: 1e+3
    aстрономические единицы: 1495978707e+2
    световые года: 94607304725808e+2
    парсеки: 30856776e+9
    мегапарсеки: 30856776e+15

  time:
    микросекунды: 1e-6
    милисекунды: 1e-3
    секунды: 1e+0
    минуты: 6e+1
    часы: 36e+2
    дни: 864e+2
    годы: 31536e+3
    столетя: 31536e+5
    тысячилетия: 31536e+6

  velosity:
    мкм / c: 1e-6
    мм / с: 1e-3
    м / с: 1e+0
    км / с: 1e+3
    скорости света: 299792458e+0

  charge:
    микрокулон: 1e-6
    миликулон: 1e-3
    кулон: 1e+0
    килокулон: 1e+3

  mass:
    микрограммы: 1e-9
    милиграммы: 1e-6
    граммы: 1e-3
    килограммы: 1e+0
    тонны: 1e+3
    массы Солнца: 1.989e+30

  electricity:
    мкВ / см: 1e-4
    мВ / см: 1e-1

  magnetic:
    мкT: 1e-6
    мT: 1e-3
    T: 1e+0

  angle:
    градусы: "0.017453292519943295"
    радианы: "1"

CASES:

  ####################### GENERAL #######################
  dimensions:
    title: Размерность пространства моделирования
    default: "2"
    type: int
    class: dropdown
    cases:
      Двумерное пространство: "2"
      Трехмерное пространство: "3"
    dementional: false

  K:
    title: Коэффициент восстановления (для столкновений)
    default: "1"
    type: int
    class: dropdown
    cases:
      Упругие столкновения: "1"
      Неупругие столкновения: "0"
    dementional: false

  output_graphics:
    title: Графический вид анимации
    default: matplotlib
    type: str
    class: dropdown
    cases:
      Сырые данные: json
      Научный: matplotlib
      Визуальный: vispy
    dementional: false

  gravity_point_interaction:
    title: Гравитационное взаимодействие точечных объектов
    default: "True"
    type: bool
    class: checkbox
    dementional: false

  gravity_extended_interaction:
    title: Внешнее гравитационное поле
    default: "False"
    type: bool
    class: checkbox
    dementional: false

  electricity_point_interaction:
    title: Кулоновское взаимодействие
    default: "False"
    type: bool
    class: checkbox
    dementional: false

  electricity_extended_interaction:
    title: Внешнее электромагнитное поле
    default: "False"
    type: bool
    class: checkbox
    dementional: false

  step:
    title: Шаг по времени моделирования
    default: "1"
    type: float
    class: number
    minimum: "0"
    units: time
    dementional: false

  steps_number:
    title: Количество шагов / временной интервал
    default: "10"
    type: int
    class: number
    minimum: "1"
    dementional: false

  fps:
    title: Количество кадров в секунду анимации / FPS
    default: "30"
    type: int
    class: number
    minimum: "1"
    dementional: false

  frames_gap:
    title: Кадровый прыжок
    default: "1"
    type: int
    class: number
    minimum: "1"
    dementional: false

  edge:
    title: Границы пространства моделирования
    default: "1"
    type: float
    class: number
    minimum: "0"
    units: distance
    dementional: false

  scale_faktor:
    title: Масштабный фактор
    default: "1"
    type: float
    class: number
    minimum: "0"
    dementional: false

  ####################### point_objects #######################
  coords:
    title: Координаты центра
    default: "0"
    type: float
    class: number
    units: distance
    dementional: true

  speed:
    title: Начальная скорость
    default: "0"
    type: float
    class: number
    units: velosity
    dementional: true

  mass:
    title: Масса
    default: "0"
    type: float
    class: number
    units: mass
    dementional: false

  charge:
    title: Заряд
    default: "0"
    type: float
    class: number
    units: charge
    dementional: false

  radius:
    title: Радиус
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  delay:
    title: Время появления
    default: "0"
    type: float
    class: number
    units: time
    dementional: false

  trajectory:
    title: Отображать траекторию частицы
    default: "True"
    type: bool
    class: checkbox
    dementional: false

  ####################### EM_fields #######################
  electricity:
    title: Компоненты электрического поля
    default: "0"
    type: expr
    class: text
    units: electricity
    dementional: true

  magnetic:
    title: Компоненты магнитного поля
    default: "0"
    type: expr
    class: text
    units: magnetic
    dementional: true

  ####################### G_fields #######################
  gravity:
    title: Потенциал гравитационного поля
    default: "0"
    type: expr
    class: text
    dementional: false

  ####################### walls #######################
  coords_1:
    title: Координаты начала стенки
    default: "0"
    type: float
    class: number
    units: distance
    dementional: true

  coords_2:
    title: Координаты конца стенки
    default: "0"
    type: float
    class: number
    units: distance
    dementional: true

  equation_X:
    title: Параметрическое уравнение границы
    default: "0"
    type: expr
    class: text
    dementional: false

  equation_Y:
    title: Параметрическое уравнение границы
    default: "0"
    type: expr
    class: text
    dementional: false

  u_s:
    title: Начальное значение параметра
    default: "0"
    type: float
    class: number
    dementinal: false

  u_f:
    title: Конечное значение параметра
    default: "0"
    type: float
    class: number
    dementinal: false

  number_of_divisions:
    title: Число разбиений интервала изменения параметра
    default: "1"
    type: int
    class: number
    dementinal: false

  elasticity:
    title: Коэффициент эластичности стенки
    default: "1"
    type: float
    class: number
    dementional: false

  ####################### general generators #######################
  particals_number:
    title: Количество точек
    default: "0"
    type: int
    class: number
    dementional: false

  equal_parameters:
    title: Сделать все объекты одинаковыми
    default: "True"
    type: bool
    class: checkbox
    dementional: false

  radius_scale:
    title: Масштабы радиусов точек
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  mass_scale:
    title: Масштаб масс точек
    default: "1"
    type: float
    class: number
    units: mass
    dementional: false

  charge_scale:
    title: Масштаб зарядов точек
    default: "1"
    type: float
    class: number
    units: charge
    dementional: false

  delay_scale:
    title: Масштаб задержки возникновения точек
    default: "1"
    type: float
    class: number
    units: time
    dementional: false

  ####################### random_generators #######################
  coordinate_scale:
    title: Масштаб координат точек
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  velocity_scale:
    title: Масштаб скоростей точек
    default: "1"
    type: float
    class: number
    units: velosity
    dementional: false

  ####################### ring_generator #######################
  mass_center:
    title: Масса центрального тела
    default: "0"
    type: float
    class: number
    units: mass
    dementional: false

  coords_center:
    title: Координаты центрального тела
    default: "0"
    type: float
    class: number
    units: distance
    dementional: true

  speed_center:
    title: Компоненты скорости центрального тела
    default: "0"
    type: float
    class: number
    units: velosity
    dementional: true

  ring_radius:
    title: Радиус кольца
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  point_velocity:
    title: Модуль скорости точек
    default: "0"
    type: float
    class: number
    units: velosity
    dementional: false

  ####################### ellipse_generators #######################
  major_axis:
    title: Большая полуось эллипса
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  exentricity:
    title: Эксцентриситет
    default: "0"
    type: float
    class: number
    dementional: false

  focus:
    title: Положение фокуса
    default: "0"
    type: int
    class: dropdown
    cases:
      Правый: "0"
      Левый: "1"
    dementional: false

  apside_angle:
    title: Угол поворота линии апсид эллипса относительно оси Ох
    default: "0"
    type: float
    class: number
    units: angle
    dementional: false

GENERAL:
  - dimensions
  - K
  - output_graphics
  - gravity_point_interaction
  - gravity_extended_interaction
  - electricity_point_interaction
  - electricity_extended_interaction
  - trajectory
  - step
  - steps_number
  - fps
  - frames_gap
  - edge
  - scale_faktor

OBJECTS:

  point_objects:
    title: Единичный объект
    cases:
      - coords
      - speed
      - mass
      - charge
      - radius
      - delay
      - trajectory

  EM_fields:
    title: Электромагнитное поле
    cases:
      - electricity
      - magnetic

  G_fields:
    title: Гравитационное поле
    cases:
      - gravity

  wall_objects:
    title: Стенка
    cases:
      - coords_1
      - coords_2
      - elasticity

  complex_wall:
    title: Сложная стенка
    cases:
      - equation_X
      - equation_Y
      - u_s
      - u_f
      - number_of_divisions
      - elasticity

  random_generators:
    title: Генератор произвольного распределения объектов
    cases:
      - particals_number
      - equal_parameters
      - radius_scale
      - mass_scale
      - charge_scale
      - delay_scale
      - coordinate_scale
      - velocity_scale

  ring_generator:
    title: Генератор кругового распределения объектов
    cases:
      - particals_number
      - equal_parameters
      - radius_scale
      - mass_scale
      - charge_scale
      - delay_scale
      - mass_center
      - coords_center
      - speed_center
      - ring_radius
      - point_velocity

  ellipse_generators:
    title: Генератор эллиптического распределения объектов
    cases:
      - particals_number
      - equal_parameters
      - radius_scale
      - mass_scale
      - charge_scale
      - delay_scale
      - mass_center
      - coords_center
      - speed_center
      - major_axis
      - exentricity
      - focus
      - apside_angle
