version: '3.8'

services:
  wsserver:
    container_name: wsserver
    build: .
    depends_on:
      - postgres
    ports:
      - "8007:8080"
    volumes:
      - ${PWD}/server/app:/usr/src/app
      - /var/astromodel:/var/astromodel
    environment:
      - MODULE_NAME=main
    healthcheck:
     test: ["CMD-SHELL", "curl -m 1 -i -N \
       -H \"Connection: Upgrade\" \
       -H \"Upgrade: websocket\" \
       -H \"Sec-WebSocket-Version: 13\" \
       -H \"Sec-WebSocket-Key: eGjlIHFhbKBsAABub11jZQ==\" \
       -X GET http://localhost:8080/health | grep Sec-WebSocket-Accept || exit 1"]
     interval: 10s
     timeout: 10s
     retries: 5

networks:
  default:
    external:
      name: astro-net
