UNITS:

  distance:
    микрометры: 1e-6
    милиметры: 1e-3
    метры: 1e+0
    километры: 1e+3
    aстрономические единицы: 1495978707e+2
    световые года: 94607304725808e+2
    парсеки: 30856776e+9
    мегапарсеки: 30856776e+15

  mass:
    микрограммы: 1e-9
    милиграммы: 1e-6
    граммы: 1e-3
    килограммы: 1e+0
    тонны: 1e+3
    массы Солнца: 1.989e+30

CASES:

  task_name:
    title: Выберите уравнение
    default: "Poisson"
    type: str
    class: dropdown
    cases:
      Уравнение Пуассона: "Poisson"
      Уравнение теплопроводности: "Heat"
    dementional: false

  mesh_name:
    title: Введите имя файла с сеткой
    default: "mesh_name.xml"
    type: str
    class: text
    dementional: false

  source:
    title: Функция источника
    default: "0"
    type: str
    class: text
    dementional: false

  kappa:
    title: Фактор нелинейности
    default: "1"
    type: str
    class: text
    dementional: false

  t_0:
    title: Начальное время
    default: "0"
    type: str
    class: text
    dementional: false

  t_f:
    title: Конечное время
    default: "0"
    type: str
    class: text
    dementional: false

  ics:
    title: Начальное условие
    default: "0"
    type: str
    class: text
    dementional: false

  N:
    title: Число шагов
    default: "1"
    type: str
    class: text
    dementional: false

  condition_type:
    title: Тип граничного условия
    default: "Dirichlet"
    type: str
    class: dropdown
    cases:
      Дирихле: "Dirichlet"
      Неймана: "Neumann"
    dementional: false

  description:
    title: Описание границы
    default: "on_boundary"
    type: str
    class: text
    dementional: false

  condition:
    title: Граничное условие
    default: "0"
    type: str
    class: text
    dementional: false

  notation:
    title: Синтаксис граничного условия
    default: "EXPR"
    type: str
    class: dropdown
    cases:
      выражение: "EXPR"
      sympy: "SYM"
    dementional: false

  mass_obj:
    title: Масса тела
    default: "0"
    type: float
    class: number
    units: mass
    dementional: false

  x:
    title: Координата Х
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  y:
    title: Координата Y
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  r:
    title: Радиус объекта
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  edge:
    title: Границы пространства
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  ncells:
    title: Количесвто конечных элементов
    default: "0"
    type: int
    class: number
    dementional: false

GENERAL:
  - task_name
  - source
  - kappa
  - mesh_name
  - t_0
  - t_f
  - N
  - ics

OBJECTS:

  scalar_functions:
    title: Граница и условие на ней
    cases:
      - condition_type
      - description
      - condition
      - notation

  mass_object:
    title: Массивный объект
    cases:
      - mass_obj
      - x
      - y
      - r
