UNITS:

  distance:
    микрометры: 1e-6
    милиметры: 1e-3
    метры: 1e+0
    километры: 1e+3
    aстрономические единицы: 1495978707e+2
    световые года: 94607304725808e+2
    парсеки: 30856776e+9
    мегапарсеки: 30856776e+15

  angle:
    градусы: 1e+0

CASES:

  dimensions:
    title: Размерность пространства моделирования
    default: "2"
    type: int
    class: dropdown
    dementional: false
    cases:
      Двумерное пространство: "2"
      Трехмерное пространство: "3"

  mesh:
    title: Способ задания сетки
    default: generator
    type: str
    class: dropdown
    dementional: false
    cases:
      Генератор сетки: generator
      Указание областей: domains

  output_file:
    title: Результат
    default: matplotlib
    type: str
    class: dropdown
    dementional: false
    cases:
      Таблица (xmls): xmls
      Графический (png): matplotlib
      Векторный (vtk and pvd): vtk

  divisions:
    title: Количество интервалов разбиения вдоль одного измерения
    default: "100"
    type: int
    class: number
    dementional: false

  invert:
    title: Знак добавления области (+ или -)
    default: "False"
    type: bool
    class: dropdown
    cases:
      +: "False"
      -: "True"
    dementional: false

  angle_of_rotation:
    title: Угол поворота области
    default: "0"
    type: float
    class: number
    units: angle
    dementional: false

  rot_point_x:
    title: Координата x центра поворота области
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  rot_point_y:
    title: Координата y центра поворота области
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  rot_point_z:
    title: Координата z центра поворота области
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  rec_x0:
    title: Координата х левого нижнего края
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  rec_x1:
    title: Координата х правого верхнего края
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  rec_y0:
    title: Координата у левого нижнего края
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  rec_y1:
    title: Координата у правого верхнего края
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  circ_x_centre:
    title: Координата х центра
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  circ_y_centre:
    title: Координата у центра
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  circ_radius:
    title: Радиус окружности
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  ell_x_centre:
    title: Координата х центра
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  ell_y_centre:
    title: Координата у центра
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  ell_a:
    title: Большая полуось эллипса
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  ell_b:
    title: Малая полуось эллипса
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  sphere_x_centre:
    title: Координата х центра
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  sphere_y_centre:
    title: Координата y центра
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  sphere_z_centre:
    title: Координата z центра
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  sphere_a:
    title: x-полуось эллипсоида
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  sphere_b:
    title: y-полуось эллипсоида
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  sphere_c:
    title: z-полуось эллипсоида
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  parall_x0:
    title: Координата x левого нижнего угла
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  parall_x1:
    title: Координата x правого верхнего угла
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  parall_y0:
    title: Координата y левого нижнего угла
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  parall_y1:
    title: Координата y правого верхнего угла
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  parall_z0:
    title: Координата z левого нижнего угла
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  parall_z1:
    title: Координата z правого верхнего угла
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  cylinder_x0:
    title: Координата x нижнего основания
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  cylinder_x1:
    title: Координата x верхнего основания
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  cylinder_y0:
    title: Координата y нижнего основания
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  cylinder_y1:
    title: Координата y верхнего основания
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  cylinder_z0:
    title: Координата z нижнего основания
    default: "0"
    type: float
    class: number
    units: distance
    dementional: false

  cylinder_z1:
    title: Координата z верхнего основания
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  cyl_radius0:
    title: Радиус нижнего основания
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  cyl_radius1:
    title: Радиус верхнего основания
    default: "1"
    type: float
    class: number
    units: distance
    dementional: false

  number_of_cells_in_an_interval:
    title: Количество ячеек
    default: "1"
    type: float
    class: number
    dementional: false

  number_of_cells_in_x_direction:
    title: Количество ячеек по x
    default: "1"
    type: float
    class: number
    dementional: false

  number_of_cells_in_y_direction:
    title: Количество ячеек по y
    default: "1"
    type: float
    class: number
    dementional: false

  number_of_cells_in_z_direction:
    title: Количество ячеек по z
    default: "1"
    type: float
    class: number
    dementional: false

  direction_of_the_diagonals:
    title: Направление диагоналей ячейки
    default: right
    type: str
    class: dropdown
    dementional: false
    cases:
      Вправо: right
      Влево: left
      Право/Лево: right"/"left
      Лево/Право: left"/"right
      Перекрёстное: crossed

GENERAL:

  - dimensions
  - output_file
  - mesh
  - divisions

OBJECTS:

  rectangles:
    title: Прямоугольник
    cases:
      - invert
      - rec_x0
      - rec_x1
      - rec_y0
      - rec_y1
      - angle_of_rotation
      - rot_point_x
      - rot_point_y

  circles:
    title: Круг
    cases:
      - invert
      - circ_x_centre
      - circ_y_centre
      - circ_radius
      - angle_of_rotation
      - rot_point_x
      - rot_point_y

  ellipses:
    title: Эллипс
    cases:
      - invert
      - ell_x_centre
      - ell_y_centre
      - ell_a
      - ell_b
      - angle_of_rotation
      - rot_point_x
      - rot_point_y

  ellipsoides:
    title: Эллипсоид
    cases:
      - invert
      - sphere_x_centre
      - sphere_y_centre
      - sphere_z_centre
      - sphere_a
      - sphere_b
      - sphere_c

  parallelepipeds:
    title: Параллелепипед
    cases:
      - invert
      - parall_x0
      - parall_x1
      - parall_y0
      - parall_y1
      - parall_z0
      - parall_z1

  cylinders:
    title: Цилиндр
    cases:
      - invert
      - cylinder_x0
      - cylinder_y0
      - cylinder_z0
      - cyl_radius0
      - cylinder_x1
      - cylinder_y1
      - cylinder_z1
      - cyl_radius1

  unitintervalmesh:
    title: Интервал (0,1)
    cases:
      - number_of_cells_in_an_interval

  unitsquaremesh:
    title: Треугольная сетка двумерного единичного квадрата
    cases:
      - number_of_cells_in_x_direction
      - number_of_cells_in_y_direction
      - direction_of_the_diagonals

  rectanglemesh:
    title: Треугольная сетка двумерного прямоугольника
    cases:
      - parall_x0
      - parall_y0
      - parall_x1
      - parall_y1
      - number_of_cells_in_x_direction
      - number_of_cells_in_y_direction
      - direction_of_the_diagonals

  unitcubemesh:
    title: Тетраэдральная сетка трехмерного единичного куба
    cases:
      - number_of_cells_in_x_direction
      - number_of_cells_in_y_direction
      - number_of_cells_in_z_direction

  boxmesh:
    title: Тетраэдрическая сетка трехмерной прямоугольной призмы
    cases:
      - parall_x0
      - parall_y0
      - parall_z0
      - parall_x1
      - parall_y1
      - parall_z1
      - number_of_cells_in_x_direction
      - number_of_cells_in_y_direction
      - number_of_cells_in_z_direction
