UNITS:

  distance:
    микрометры: 1e-6
    милиметры: 1e-3
    метры: 1e+0
    километры: 1e+3
    aстрономические единицы: 1495978707e+2
    световые года: 94607304725808e+2
    парсеки: 30856776e+9
    мегапарсеки: 30856776e+15

CASES:

  dimensions:
    title: Размерность пространства моделирования
    default: "2"
    type: int
    class: dropdown
    dementional: false
    cases:
      Двумерное пространство: "2"
      Трехмерное пространство: "3"

  mesh:
    title: Способ задания сетки
    default: generator
    type: str
    class: dropdown
    dementional: false
    cases:
      Генератор сетки: generator
      Указание областей: domains

  output_file:
    title: Результат
    default: matplotlib
    type: str
    class: dropdown
    dementional: false
    cases:
      Таблица (xmls): xmls
      Графический (png): matplotlib
      Векторный (vtk and pvd): vtk

  symbol:
    title: Знак добавления области (+ или -)
    default: +
    type: str
    class: text
    dementional: false

  rec_x0:
    title: Координата х левого нижнего края
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  rec_x1:
    title: Координата х правого верхнего края
    default: "1"
    type: str
    class: text
    units: distance
    dementional: false

  rec_y0:
    title: Координата у левого нижнего края
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  rec_y1:
    title: Координата у правого верхнего края
    default: "1"
    type: str
    class: text
    units: distance
    dementional: false

  circ_x_centre:
    title: Координата х центра
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  circ_y_centre:
    title: Координата у центра
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  circ_radius:
    title: Радиус окружности
    default: "1"
    type: str
    class: text
    units: distance
    dementional: false

  ell_x_centre:
    title: Координата х центра
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  ell_y_centre:
    title: Координата у центра
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  ell_a:
    title: Большая полуось эллипса
    default: "1"
    type: str
    class: text
    units: distance
    dementional: false

  ell_b:
    title: Малая полуось эллипса
    default: "1"
    type: str
    class: text
    units: distance
    dementional: false



GENERAL:

  - dimensions
  - output_file
  - mesh

OBJECTS:

  rectangles:
    title: Прямоугольник
    cases:
      - symbol
      - rec_x0
      - rec_x1
      - rec_y0
      - rec_y1

  circles:
    title: Круг
    cases:
      - symbol
      - circ_x_centre
      - circ_y_centre
      - circ_radius

  ellipses:
    title: Эллипс
    cases:
      - symbol
      - ell_x_centre
      - ell_y_centre
      - ell_a
      - ell_b
