UNITS:

  distance:
    микрометры: 1e-6
    милиметры: 1e-3
    метры: 1e+0
    километры: 1e+3
    aстрономические единицы: 1495978707e+2
    световые года: 94607304725808e+2
    парсеки: 30856776e+9
    мегапарсеки: 30856776e+15

CASES:

  dimensions:
    title: Размерность пространства моделирования
    default: 2
    type: int
    class: dropdown
    cases:
      Двумерное пространство: 2
      Трехмерное пространство: 3
    dementional: false

  K:
    title: Коэффициент восстановления (для столкновений)
    default: 1
    type: int
    class: dropdown
    cases:
      Упругие столкновения: 1
        Неупругие столкновения: 0
    dementional: false

  output_graphics:
    title: Графический вид анимации
    default: matplotlib
    type: str
    class: dropdown
    cases:
      Сырые данные: json
      Научный: matplotlib
      Визуальный: vispy
    dementional: false


GENERAL:
  - rocket_name
  - rocket_time
  - jet_count
  - post_in_news


OBJECTS:

  astronauts:
    title: Астронафт
    cases:
      - astronaut_name
      - astronaut_weight
      - astronaut_age
      - astronaut_sex
