UNITS:

  distance:
    микрометры: 1e-6
    милиметры: 1e-3
    метры: 1e+0
    километры: 1e+3
    aстрономические единицы: 1495978707e+2
    световые года: 94607304725808e+2
    парсеки: 30856776e+9
    мегапарсеки: 30856776e+15

CASES:

  dimensions:
    title: Размерность пространства моделирования
    default: "2"
    type: int
    class: dropdown
    dementional: false
    cases:
      Двумерное пространство: "2"
      Трехмерное пространство: "3"

  mesh:
    title: Способ задания сетки
    default: generator
    type: str
    class: dropdown
    dementional: false
    cases:
      Генератор сетки: generator
      Указание областей: domains

  output_files:
    title: Результат
    default: matplotlib
    type: str
    class: dropdown
    dementional: false
    cases:
      Таблица (xmls): xmls
      Графический (png): matplotlib
      Векторный (vtk and pvd): vtk

  x:
    title: x
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  y:
    title: y
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  z:
    title: z
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  point_x:
    title: Точка
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  point_y:
    title: Точка
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  radius:
    title: Радиус
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  vertex:
    title: Количество вершин
    default: "10"
    type: int
    class: text
    dementional: false

  segments:
    title: Сегменты
    default: "32"
    type: int
    class: text
    dementional: false

  a:
    title: Большая полуось
    default: "1"
    type: str
    class: text
    units: distance
    dementional: false

  b:
    title: Малая полуось
    default: "1"
    type: str
    class: text
    units: distance
    dementional: false

  h:
    title: Высота
    default: "1"
    type: str
    class: text
    units: distance
    dementional: false

  d:
    title: Диаметр основания
    default: "1"
    type: str
    class: text
    units: distance
    dementional: false

  param_for_csg:
    title: Хер его знает, что за параметр?
    default: "1"
    type: str
    class: text
    units: distance
    dementional: false

  options:
    title: Опции генератора сеток
    default: None
    type: str
    class: dropdown
    dementional: false
    cases:
      left: left
      right: right
      right/left: right/left
      crossed: crossed

  start:
    title: Начало
    default: "0"
    type: str
    class: text
    units: distance
    dementional: false

  stop:
    title: Конец
    default: "10"
    type: str
    class: text
    units: distance
    dementional: false

GENERAL:

  - dimensions
  - output_files
  - mesh

OBJECTS:

  Rectangle:
    title: Прямоугольник
    cases:
      - point_x
      - point_y

  Circle:
    title: Круг
    cases:
      - point_x
      - point_y
      - radius

  Ellipse:
    title: Эллипс
    cases:
      - point_x
      - point_y
      - a
      - b
      - segments

  Cylinder:
    title: Цилиндр
    cases:
      - point_x
      - point_y
      - h
      - d
      - vertex

  Cone:
    title: Диск
    cases:
      - point_x
      - point_y
      - h
      - d
      - vertex

  Ellipsoid:
    title: Эллипсоид
    cases:
      - point_x
      - point_y
      - a
      - b
      - h
      - vertex

  UnitIntervalMesh:
    title: Генератор интервала
    cases:
      - start
      - stop
      - options

  RectangleMesh:
    title: Генератор прямоугольной сетки
    cases:
      - point_x
      - point_y
      - options

  UnitCubeMesh:
    title: Генератор прямоугольной сетки
    cases:
      - x
      - y
      - z
