version: "3.8"

services:
    astromodel:
        container_name: astromodel
        build: .
        restart: always
        ports:
            - 8080:80
        volumes:
            - /var/astromodel:/var/astromodel
        environment:
            - MODULE_NAME=main
            - PYTHONDONTWRITEBYTECODE=x
            - PYTHONUNBUFFERED=x
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "wget -O /dev/null http://localhost:80/api/ || exit 1",
                ]
            interval: 10s
            timeout: 10s
            retries: 5

networks:
    default:
        external: true
        name: astro-net
