version: '3.8'

services:
  localrun:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/localrun/Dockerfile
    volumes:
      - ${PWD}/modeling_module/physical_problems/${PROBLEM}/results:/usr/src/modeling_module/physical_problems/${PROBLEM}/results